local predefined = require "custom.predefined_hls"

local theme = {
  ColorColumn = { bg = "o_bluegray1" },
  Conceal = { bg = "NONE" },
  CurSearch = { link = "IncSearch" },
  CursorColumn = { bg = "o_background1" },
  CursorLine = { bg = "o_background1" },
  CursorLineNr = { fg = "o_text" },
  DarkenedPanel = { bg = "g_panel" },
  DarkenedStatusline = { bg = "g_panel" },

  Directory = { fg = "o_blue3", bg = "NONE" },
  ErrorMsg = { fg = "o_pink3", bold = true },
  FloatBorder = { fg = "g_border" },
  FloatTitle = { fg = "o_bluegray2" },
  FoldColumn = { fg = "o_bluegray2" },
  Folded = { fg = "o_text", bg = "g_panel" },
  IncSearch = { fg = "o_background3", bg = "o_blue2", bold = true },
  LineNr = { fg = "o_bluegray3" },
  MatchParen = { bg = "o_bluegray3", fg = "o_background3" },
  ModeMsg = { fg = "o_blue3" },
  MoreMsg = { fg = "o_blue3" },
  NonText = { fg = "o_blue4" },
  Normal = { fg = "o_text", bg = "g_background" },
  NormalFloat = { fg = "o_text", bg = "g_panel" },
  NormalNC = { fg = "o_text", bg = "g_background" },
  NvimInternalError = { fg = "o_white", bg = "o_pink3" },
  Pmenu = { fg = "o_bluegray1", bg = "g_panel" },
  PmenuSbar = { bg = "o_bluegray2" },
  PmenuSel = { fg = "o_text", bg = "o_background1" },
  PmenuThumb = { bg = "o_bluegray3" },
  Question = { fg = "o_text" },
  RedrawDebugClear = { fg = "o_white", bg = "o_yellow" },
  RedrawDebugComposed = { fg = "o_white", bg = "o_teal2" },
  RedrawDebugRecompose = { fg = "o_white", bg = "o_pink3" },
  Search = { bg = { "o_blue3", -25 }, bold = true, nocombine = true },
  SpecialKey = { fg = "o_teal1" },
  SpellBad = { sp = "o_pink3", undercurl = true },
  SpellCap = { sp = "o_blue1", undercurl = true },
  SpellLocal = { sp = "o_yellow", undercurl = true },
  SpellRare = { sp = "o_blue1", undercurl = true },
  SignColumn = { fg = "o_text", bg = "NONE" },
  StatusLine = { fg = "o_blue3", bg = "g_panel" },
  StatusLineNC = { fg = "o_blue3", bg = "g_background" },
  StatusLineTerm = { link = "StatusLine" },
  StatusLineTermNC = { link = "StatusLineNC" },
  TabLine = { fg = "o_blue3", bg = "g_panel" },
  TabLineFill = { bg = "g_panel" },
  TabLineSel = { fg = "o_text", bg = "o_background1" },
  Title = { fg = "o_text" },
  VertSplit = { fg = "NONE", bg = "NONE" },
  Visual = { fg = "o_text", bg = "o_bluegray3" },
  WarningMsg = { fg = "o_yellow" },
  Whitespace = { fg = "o_bluegray3" },
  WildMenu = { link = "IncSearch" },

  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = "o_pink3" },
  Todo = { bg = "NONE", fg = "o_blue1", bold = true },
  qfLineNr = { fg = "o_bluegray3" },
  qfFileName = { fg = "o_bluegray2" },
  htmlH1 = { fg = "o_teal1", bold = true },
  htmlH2 = { fg = "o_teal1", bold = true },
  -- mkdCodeDelimiter = { bg = "o_background3", fg = "o_text" },
  -- mkdCodeStart = { fg = "o_teal2", bold = true },
  -- mkdCodeEnd = { fg = "o_teal2", bold = true },
  -- mkdLink = { fg = "o_blue1", underline = true },
  -- markdownHeadingDelimiter = { fg = "o_blue4", bold = true },
  -- markdownCode = { fg = "o_bluegray1" },
  -- markdownCodeBlock = { fg = "o_teal2" },
  -- markdownH1 = { fg = "o_blue2", bold = true },
  -- markdownH2 = { fg = "o_blue2", bold = true },
  -- markdownH3 = { fg = "o_blue2", bold = true },
  -- markdownH4 = { fg = "o_blue2", bold = true },
  -- markdownLinkText = { fg = "o_blue1", underline = true },

  DiagnosticError = { fg = "g_error" },
  DiagnosticHint = { fg = "g_hint" },
  DiagnosticInfo = { fg = "g_info" },
  DiagnosticWarn = { fg = "g_warn" },
  DiagnosticDefaultError = { fg = "g_error" },
  DiagnosticDefaultHint = { fg = "g_hint" },
  DiagnosticDefaultInfo = { fg = "g_info" },
  DiagnosticDefaultWarn = { fg = "g_warn" },
  DiagnosticFloatingError = { fg = "g_error" },
  DiagnosticFloatingHint = { fg = "g_hint" },
  DiagnosticFloatingInfo = { fg = "g_info" },
  DiagnosticFloatingWarn = { fg = "g_warn" },
  DiagnosticSignError = { fg = "g_error" },
  DiagnosticSignHint = { fg = "g_hint" },
  DiagnosticSignInfo = { fg = "g_info" },
  DiagnosticSignWarn = { fg = "g_warn" },
  DiagnosticStatusLineError = { fg = "g_error", bg = "g_panel" },
  DiagnosticStatusLineHint = { fg = "g_hint", bg = "g_panel" },
  DiagnosticStatusLineInfo = { fg = "g_info", bg = "g_panel" },
  DiagnosticStatusLineWarn = { fg = "g_warn", bg = "g_panel" },
  DiagnosticUnderlineError = { sp = "g_error", undercurl = true },
  DiagnosticUnderlineHint = { sp = "g_hint", undercurl = true },
  DiagnosticUnderlineInfo = { sp = "g_info", undercurl = true },
  DiagnosticUnderlineWarn = { sp = "g_warn", undercurl = true },
  DiagnosticVirtualTextError = { fg = "g_error" },
  DiagnosticVirtualTextHint = { fg = "g_hint" },
  DiagnosticVirtualTextInfo = { fg = "g_info" },
  DiagnosticVirtualTextWarn = { fg = "g_warn" },

  Constant = { fg = "o_pink2" },
  Variable = { fg = "o_bluegray1" },
  String = { fg = "o_teal2" },
  Character = { fg = "o_pink3" },
  Number = { fg = "o_teal1" },
  Boolean = { fg = "o_teal1" },
  Float = { fg = "o_teal1" },
  Identifier = { fg = "o_bluegray1" },
  Function = { fg = "o_teal1" },
  Statement = { fg = "o_text" },
  Conditional = { fg = "o_bluegray1" },
  Repeat = { fg = "o_blue3" },
  Label = { fg = "o_text" },
  Operator = { fg = "o_blue2" },
  Keyword = { fg = { "o_pink3", -10 } },
  Exception = { fg = "o_blue3" },
  PreProc = { fg = "o_text" },
  -- Include = { fg = "o_bluegray1" },
  Include = { link = "Keyword" },
  Type = { fg = "o_text" },
  Special = { fg = "o_bluegray2" },
  -- Tag = { fg = "o_text" },
  Tag = { link = "Keyword" },
  Delimiter = { fg = "o_bluegray1" },
  SpecialComment = { fg = "o_bluegray1" },
  Comment = { fg = "o_bluegray3" },
  -- ["@variable"] = { fg = "o_text" },
  ["@variable"] = { link = "Variable" },
  ["@boolean"] = { link = "Boolean" },
  ["@comment"] = { link = "Comment" },
  ["@variable.builtin"] = { fg = "o_blue2" },
  ["@exception"] = { link = "Keyword" },
  ["@constant"] = { fg = "o_pink2" },
  ["@constant.builtin"] = { fg = "o_blue2" },
  ["@constant.falsy"] = { fg = "o_pink3" },
  ["@constructor"] = { fg = "o_teal1" },
  ["@attribute"] = { link = "Keyword" },
  ["@field"] = { link = "Variable" },
  ["@function.builtin"] = { fg = "o_blue2" },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = "o_bluegray1" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = "o_teal2" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.operator"] = { fg = "o_teal1" },
  ["@label"] = { fg = "o_blue3" },
  ["@method"] = { fg = "o_teal1" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { fg = "o_bluegray1" },
  ["@property"] = { fg = "o_blue2" },
  ["@punctuation.delimiter"] = { fg = "g_punctuation" },
  ["@punctuation.special"] = { fg = "g_punctuation" },
  ["@punctuation.bracket"] = { fg = "o_text" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = "o_pink3" },
  ["@tag"] = { link = "Tag" },
  ["@tag.delimiter"] = { link = "Tag" },
  ["@tag.attribute"] = { link = "Constant" },
  ["@text"] = { fg = "o_text" },
  ["@text.uri"] = { fg = "o_teal2", underline = true },
  ["@text.danger"] = { link = "ErrorMsg" },
  ["@title"] = { fg = "g_h1", bold = true },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Type" },
  ["@type.qualifier"] = { link = "Keyword" },

  LspReferenceText = { bg = "o_blue2" },
  LspReferenceRead = { bg = "o_blue2" },
  LspReferenceWrite = { bg = "o_blue2" },
  LspCodeLens = { fg = "o_bluegray1" },
  LspCodeLensSeparator = { fg = "o_bluegray3" },

  GitSignsAdd = { fg = "g_git_add" },
  GitSignsChange = { fg = "g_git_change" },
  GitSignsDelete = { fg = "g_git_delete" },
  SignAdd = { link = "GitSignsAdd" },
  SignChange = { link = "GitSignsChange" },
  SignDelete = { link = "GitSignsDelete" },
  diffAdded = { link = "GitSignsAdd" },
  diffChanged = { link = "GitSignsChange" },
  diffRemoved = { link = "GitSignsRemoved" },

  NvimTreeCursorLine = { link = "CursorLine" },
  NvimTreeEmptyFolderName = { fg = "o_bluegray3" },
  NvimTreeFileDeleted = { fg = "o_pink3" },
  NvimTreeFileDirty = { fg = "o_blue4" },
  NvimTreeFileMerge = { fg = "o_blue2" },
  NvimTreeFileNew = { fg = "o_teal1" },
  NvimTreeFileRenamed = { fg = "o_bluegray3" },
  NvimTreeFileStaged = { fg = "o_blue1" },
  NvimTreeFolderIcon = { fg = "o_blue3" },
  NvimTreeFolderName = { fg = "o_blue3" },
  NvimTreeGitDeleted = { fg = "g_git_delete" },
  NvimTreeGitDirty = { fg = "g_git_dirty" },
  NvimTreeGitIgnored = { fg = "g_git_ignore" },
  NvimTreeGitMerge = { fg = "g_git_merge" },
  NvimTreeGitNew = { fg = "g_git_add" },
  NvimTreeGitRenamed = { fg = "g_git_rename" },
  NvimTreeGitStaged = { fg = "g_git_stage" },
  NvimTreeImageFile = { fg = "o_text" },
  NvimTreeNormal = { fg = "o_text" },
  NvimTreeOpenedFile = { fg = "o_text", bg = "o_background1" },
  NvimTreeOpenedFolderName = { link = "NvimTreeFolderName" },
  NvimTreeRootFolder = { fg = "o_teal1" },
  NvimTreeSpecialFile = { link = "NvimTreeNormal" },
  NvimTreeWindowPicker = { fg = "g_bg", bg = "o_bluegray1" },

  WhichKey = { fg = "o_text" },
  WhichKeyGroup = { fg = "o_blue3" },
  WhichKeySeparator = { fg = "o_bluegray2" },
  WhichKeyDesc = { fg = "o_teal2" },
  WhichKeyFloat = { bg = "g_panel" },
  WhichKeyValue = { fg = "o_text" },

  IndentBlanklineChar = { fg = "o_background1" },
  IndentBlanklineContextChar = { fg = "o_bluegray2", nocombine = true },
  IndentBlanklineContextStart = { sp = "o_bluegray2", bg = "IlluminatedWordText", underline = true },
  IndentBlanklineSpaceChar = { link = "Whitespace" },
  IndentBlanklineSpaceCharBlankline = { link = "Whitespace" },

  IlluminatedWordRead = { bg = { "o_background1", 5 } },
  IlluminatedWordText = { bg = { "o_background1", 5 } },
  IlluminatedWordWrite = { bg = { "o_background1", 5 } },

  CmpItemAbbr = { fg = "o_bluegray2" },
  CmpItemAbbrDeprecated = { fg = "o_pink3", strikethrough = true },
  CmpItemAbbrMatch = { fg = "o_text", bold = true },
  CmpItemAbbrMatchFuzzy = { fg = "o_teal1", bold = true },
  CmpItemKind = { fg = "o_blue3" },
  CmpItemKindClass = { fg = "o_yellow" },
  CmpItemKindFunction = { fg = "o_blue1" },
  CmpItemKindInterface = { fg = "o_blue2" },
  CmpItemKindMethod = { fg = "o_pink3" },
  CmpItemKindSnippet = { fg = "o_bluegray1" },
  CmpItemKindVariable = { fg = "o_teal1" },

  LspSignatureActiveParameter = { bg = "o_bluegray1" },

  TelescopeBorder = { fg = "g_border" },
  TelescopeMatching = { bold = true },
  TelescopeNormal = { fg = "o_text" },
  TelescopePromptNormal = { fg = "o_text" },
  TelescopePromptPrefix = { fg = "o_bluegray1" },
  TelescopeSelection = { link = "CursorLine" },
  TelescopeSelectionCaret = { fg = "o_pink2", bg = "o_bluegray1" },
  TelescopeTitle = { fg = "o_bluegray2" },

  HopNextKey = { fg = { "o_blue1", 10 } },
  HopNextKey1 = { fg = { "o_teal1", 10 } },
  HopNextKey2 = { fg = "o_teal2" },
  HopUnmatched = { fg = { "o_bluegray3", -10 } },
  HopCursor = { fg = "NONE" },

  NotifyINFOBorder = { fg = "o_teal1" },
  NotifyINFOTitle = { link = "NotifyINFOBorder" },
  NotifyINFOIcon = { link = "NotifyINFOBorder" },
  NotifyWARNBorder = { fg = "o_yellow" },
  NotifyWARNTitle = { link = "NotifyWARNBorder" },
  NotifyWARNIcon = { link = "NotifyWARNBorder" },
  NotifyDEBUGBorder = { fg = "o_blue1" },
  NotifyDEBUGTitle = { link = "NotifyDEBUGBorder" },
  NotifyDEBUGIcon = { link = "NotifyDEBUGBorder" },
  NotifyTRACEBorder = { fg = "o_blue1" },
  NotifyTRACETitle = { link = "NotifyTRACEBorder" },
  NotifyTRACEIcon = { link = "NotifyTRACEBorder" },
  NotifyERRORBorder = { fg = "o_pink3" },
  NotifyERRORTitle = { link = "NotifyERRORBorder" },
  NotifyERRORIcon = { link = "NotifyERRORBorder" },
}

local function generate()
  local M = {
    override = {},
    add = {},
  }
  for key, val in pairs(theme) do
    if predefined[key] then
      M.override[key] = val
    else
      M.add[key] = val
    end
  end

  return M
end

return generate()
