local predefined = {
  ["WhichKeyDesc"] = true,
  ["WhichKeyGroup"] = true,
  ["WhichKeyValue"] = true,
  ["WhichKey"] = true,
  ["WhichKeySeparator"] = true,
  ["TelescopeResultsDiffDelete"] = true,
  ["TelescopeBorder"] = true,
  ["TelescopePromptBorder"] = true,
  ["TelescopePromptNormal"] = true,
  ["TelescopeResultsTitle"] = true,
  ["TelescopePromptPrefix"] = true,
  ["TelescopeNormal"] = true,
  ["TelescopePreviewTitle"] = true,
  ["TelescopePromptTitle"] = true,
  ["TelescopeSelection"] = true,
  ["TelescopeResultsDiffAdd"] = true,
  ["TelescopeResultsDiffChange"] = true,
  ["TBTabTitle"] = true,
  ["TbLineThemeToggleBtn"] = true,
  ["TbLineCloseAllBufsBtn"] = true,
  ["TblineFill"] = true,
  ["TbLineBufOn"] = true,
  ["TbLineBufOff"] = true,
  ["TbLineBufOnModified"] = true,
  ["TbBufLineBufOffModified"] = true,
  ["TbLineBufOnClose"] = true,
  ["TbLineBufOffClose"] = true,
  ["TblineTabNewBtn"] = true,
  ["TbLineTabOn"] = true,
  ["TbLineTabOff"] = true,
  ["TbLineTabCloseBtn"] = true,
  ["@lsp.type.macro"] = true,
  ["@keyword.return"] = true,
  ["@lsp.type.method"] = true,
  ["Tag"] = true,
  ["@lsp.type.namespace"] = true,
  ["@operator"] = true,
  ["@lsp.type.parameter"] = true,
  ["@lsp.type.property"] = true,
  ["Structure"] = true,
  ["@lsp.type.struct"] = true,
  ["@punctuation.bracket"] = true,
  ["@lsp.type.type"] = true,
  ["Label"] = true,
  ["@lsp.type.typeParamater"] = true,
  ["@lsp.type.variable"] = true,
  ["Float"] = true,
  ["@float"] = true,
  ["@exception"] = true,
  ["@constant.macro"] = true,
  ["StorageClass"] = true,
  ["@constant"] = true,
  ["@constructor"] = true,
  ["@character"] = true,
  ["@include"] = true,
  ["@property"] = true,
  ["@field.key"] = true,
  ["@scope"] = true,
  ["@function"] = true,
  ["@attribute"] = true,
  ["Statement"] = true,
  ["@constant.builtin"] = true,
  ["Identifier"] = true,
  ["@function.macro"] = true,
  ["@lsp.type.enum"] = true,
  ["@reference"] = true,
  ["@none"] = true,
  ["@method.call"] = true,
  ["@keyword.operator"] = true,
  ["Character"] = true,
  ["@parameter"] = true,
  ["@function.call"] = true,
  ["@namespace"] = true,
  ["PreProc"] = true,
  ["@function.builtin"] = true,
  ["@method"] = true,
  ["@keyword.function"] = true,
  ["Include"] = true,
  ["Define"] = true,
  ["Keyword"] = true,
  ["Conditional"] = true,
  ["Number"] = true,
  ["Variable"] = true,
  ["Constant"] = true,
  ["Operator"] = true,
  ["Boolean"] = true,
  ["Function"] = true,
  ["String"] = true,
  ["@punctuation.delimiter"] = true,
  ["@punctuation.special"] = true,
  ["@string"] = true,
  ["@string.regex"] = true,
  ["@string.escape"] = true,
  ["@string.special"] = true,
  ["@symbol"] = true,
  ["@tag"] = true,
  ["@tag.attribute"] = true,
  ["@tag.delimiter"] = true,
  ["@text"] = true,
  ["@text.strong"] = true,
  ["@text.emphasis"] = true,
  ["@text.strike"] = true,
  ["@text.literal"] = true,
  ["@text.uri"] = true,
  ["@type.builtin"] = true,
  ["@definition"] = true,
  ["@variable"] = true,
  ["@field"] = true,
  ["@variable.builtin"] = true,
  ["Delimiter"] = true,
  ["@conditional"] = true,
  ["Repeat"] = true,
  ["Special"] = true,
  ["SpecialChar"] = true,
  ["@annotation"] = true,
  ["Todo"] = true,
  ["Typedef"] = true,
  ["@lsp.type.class"] = true,
  ["@lsp.type.decorator"] = true,
  ["Type"] = true,
  ["@lsp.type.enumMember"] = true,
  ["@error"] = true,
  ["@lsp.type.function"] = true,
  ["@lsp.type.interface"] = true,
  ["@keyword"] = true,
  ["NvimTreeGitNew"] = true,
  ["NvimTreeGitDirty"] = true,
  ["NvimTreeFolderIcon"] = true,
  ["NvimTreeFolderName"] = true,
  ["NvimTreeGitIgnored"] = true,
  ["NvimTreeOpenedFolderName"] = true,
  ["NvimTreeNormal"] = true,
  ["NvimTreeIndentMarker"] = true,
  ["NvimTreeEndOfBuffer"] = true,
  ["NvimTreeNormalNC"] = true,
  ["NvimTreeWinSeparator"] = true,
  ["NvimTreeWindowPicker"] = true,
  ["NvimTreeCursorLine"] = true,
  ["NvimTreeEmptyFolderName"] = true,
  ["NvimTreeRootFolder"] = true,
  ["NvimTreeSpecialFile"] = true,
  ["NvimTreeGitDeleted"] = true,
  ["NvDashAscii"] = true,
  ["NvDashButtons"] = true,
  ["NvChHeadred"] = true,
  ["NvChHeadblue"] = true,
  ["NvChHeading"] = true,
  ["NvChSection"] = true,
  ["NvChAsciiHeader"] = true,
  ["NvChHeadteal"] = true,
  ["NvChHeadvibrant_green"] = true,
  ["NvChHeadcyan"] = true,
  ["NvChHeadwhite"] = true,
  ["NvChHeadpurple"] = true,
  ["NvChHeadbaby_pink"] = true,
  ["NvChHeadorange"] = true,
  ["NvChHeadyellow"] = true,
  ["NvChHeadgreen"] = true,
  ["nvUpdaterTitleDone"] = true,
  ["nvUpdaterTitleFAIL"] = true,
  ["nvUpdaterProgress"] = true,
  ["nvUpdaterProgressDONE"] = true,
  ["nvUpdaterProgressFAIL"] = true,
  ["nvUpdaterCommits"] = true,
  ["nvUpdaterFAIL"] = true,
  ["nvUpdaterTitle"] = true,
  ["MasonHeader"] = true,
  ["MasonHighlight"] = true,
  ["MasonHighlightBlockBold"] = true,
  ["MasonHighlightBlock"] = true,
  ["MasonHeaderSecondary"] = true,
  ["MasonMuted"] = true,
  ["MasonMutedBlock"] = true,
  ["DiagnosticWarn"] = true,
  ["LspReferenceText"] = true,
  ["LspSignatureActiveParameter"] = true,
  ["LspReferenceRead"] = true,
  ["RenamerBorder"] = true,
  ["DiagnosticHint"] = true,
  ["DiagnosticError"] = true,
  ["RenamerTitle"] = true,
  ["DiagnosticInformation"] = true,
  ["LspReferenceWrite"] = true,
  ["diffOldFile"] = true,
  ["diffNewFile"] = true,
  ["DiffAdded"] = true,
  ["DiffModified"] = true,
  ["DiffRemoved"] = true,
  ["DiffText"] = true,
  ["gitcommitOverflow"] = true,
  ["gitcommitSummary"] = true,
  ["gitcommitComment"] = true,
  ["gitcommitUntracked"] = true,
  ["gitcommitDiscarded"] = true,
  ["gitcommitSelected"] = true,
  ["gitcommitHeader"] = true,
  ["gitcommitSelectedType"] = true,
  ["gitcommitUnmergedType"] = true,
  ["gitcommitDiscardedType"] = true,
  ["gitcommitBranch"] = true,
  ["gitcommitUntrackedFile"] = true,
  ["DiffAdd"] = true,
  ["DiffChange"] = true,
  ["gitcommitSelectedFile"] = true,
  ["gitcommitDiscardedFile"] = true,
  ["DiffDelete"] = true,
  ["gitcommitUnmergedFile"] = true,
  ["DiffChangeDelete"] = true,
  ["DevIconmp3"] = true,
  ["DevIconlua"] = true,
  ["DevIconMd"] = true,
  ["DevIcontoml"] = true,
  ["DevIconc"] = true,
  ["DevIconcss"] = true,
  ["DevIcondeb"] = true,
  ["DevIconDockerfile"] = true,
  ["DevIconhtml"] = true,
  ["DevIconjpeg"] = true,
  ["DevIconjpg"] = true,
  ["DevIconjs"] = true,
  ["DevIconkt"] = true,
  ["DevIconlock"] = true,
  ["DevIconDefault"] = true,
  ["DevIconmp4"] = true,
  ["DevIconout"] = true,
  ["DevIconpng"] = true,
  ["DevIconpy"] = true,
  ["DevIconts"] = true,
  ["DevIconttf"] = true,
  ["DevIconrb"] = true,
  ["DevIconrpm"] = true,
  ["DevIconvue"] = true,
  ["DevIconwoff"] = true,
  ["DevIconwoff2"] = true,
  ["DevIconxz"] = true,
  ["DevIconzip"] = true,
  ["DevIconZig"] = true,
  ["DevIconTSX"] = true,
  ["DevIconJSX"] = true,
  ["DevIconSvelte"] = true,
  ["DevIconJava"] = true,
  ["LazyH2"] = true,
  ["SpellLocal"] = true,
  ["SpellCap"] = true,
  ["SignColumn"] = true,
  ["SpellRare"] = true,
  ["healthSuccess"] = true,
  ["LazyReasonPlugin"] = true,
  ["LazyReasonFt"] = true,
  ["St_VisualMode"] = true,
  ["LazyReasonKeys"] = true,
  ["LazyReasonEvent"] = true,
  ["LazyReasonStart"] = true,
  ["LazyReasonRuntime"] = true,
  ["St_InsertMode"] = true,
  ["LazyReasonSource"] = true,
  ["LazyReasonImport"] = true,
  ["FloatBorder"] = true,
  ["LazyButton"] = true,
  ["St_SelectModeSep"] = true,
  ["WinSeparator"] = true,
  ["St_CommandModeSep"] = true,
  ["Error"] = true,
  ["St_ConfirmModeSep"] = true,
  ["LazyNoCond"] = true,
  ["St_ReplaceModeSep"] = true,
  ["LazyH1"] = true,
  ["St_NTerminalModeSep"] = true,
  ["NormalFloat"] = true,
  ["St_TerminalModeSep"] = true,
  ["St_ReplaceMode"] = true,
  ["St_InsertModeSep"] = true,
  ["St_SelectMode"] = true,
  ["St_VisualModeSep"] = true,
  ["LazyReasonCmd"] = true,
  ["St_NormalModeSep"] = true,
  ["St_CommandMode"] = true,
  ["St_NormalMode"] = true,
  ["St_LspStatus"] = true,
  ["St_LspStatus_Icon"] = true,
  ["St_EmptySpace2"] = true,
  ["LazyValue"] = true,
  ["St_file_sep"] = true,
  ["LazyUrl"] = true,
  ["St_cwd_text"] = true,
  ["St_cwd_sep"] = true,
  ["St_pos_sep"] = true,
  ["St_pos_icon"] = true,
  ["St_pos_text"] = true,
  ["Title"] = true,
  ["St_cwd_icon"] = true,
  ["StatusLine"] = true,
  ["LazyOperator"] = true,
  ["LazyCommit"] = true,
  ["St_file_info"] = true,
  ["St_LspProgress"] = true,
  ["St_EmptySpace"] = true,
  ["St_LspInfo"] = true,
  ["St_gitIcons"] = true,
  ["St_LspHints"] = true,
  ["Bold"] = true,
  ["LazyCommitIssue"] = true,
  ["LazyDir"] = true,
  ["St_NTerminalMode"] = true,
  ["Italic"] = true,
  ["St_lspWarning"] = true,
  ["St_lspError"] = true,
  ["CursorLine"] = true,
  ["Directory"] = true,
  ["IncSearch"] = true,
  ["LazyTaskOutput"] = true,
  ["PmenuSel"] = true,
  ["LazySpecial"] = true,
  ["SpellBad"] = true,
  ["WarningMsg"] = true,
  ["St_ConfirmMode"] = true,
  ["St_TerminalMode"] = true,
  ["ErrorMsg"] = true,
  ["CursorLineNr"] = true,
  ["LineNr"] = true,
  ["LazyProgressDone"] = true,
  ["CursorColumn"] = true,
  ["NonText"] = true,
  ["Comment"] = true,
  ["Normal"] = true,
  ["Pmenu"] = true,
  ["PmenuSbar"] = true,
  ["PmenuThumb"] = true,
  ["MatchWord"] = true,
  ["MatchParen"] = true,
  ["Search"] = true,
  ["NvimInternalError"] = true,
  ["Debug"] = true,
  ["Exception"] = true,
  ["FoldColumn"] = true,
  ["Folded"] = true,
  ["Macro"] = true,
  ["ModeMsg"] = true,
  ["MoreMsg"] = true,
  ["Question"] = true,
  ["Substitute"] = true,
  ["SpecialKey"] = true,
  ["TooLong"] = true,
  ["UnderLined"] = true,
  ["Visual"] = true,
  ["VisualNOS"] = true,
  ["WildMenu"] = true,
  ["Conceal"] = true,
  ["Cursor"] = true,
  ["ColorColumn"] = true,
  ["QuickFixLine"] = true,
  ["CmpItemAbbr"] = true,
  ["CmpItemAbbrMatch"] = true,
  ["CmpDoc"] = true,
  ["CmpDocBorder"] = true,
  ["CmpPmenu"] = true,
  ["CmpSel"] = true,
  ["CmpItemKindConstant"] = true,
  ["CmpItemKindFunction"] = true,
  ["CmpItemKindIdentifier"] = true,
  ["CmpItemKindField"] = true,
  ["CmpItemKindVariable"] = true,
  ["CmpItemKindSnippet"] = true,
  ["CmpItemKindText"] = true,
  ["CmpItemKindStructure"] = true,
  ["CmpItemKindType"] = true,
  ["CmpItemKindKeyword"] = true,
  ["CmpItemKindMethod"] = true,
  ["CmpItemKindConstructor"] = true,
  ["CmpItemKindFolder"] = true,
  ["CmpItemKindModule"] = true,
  ["CmpItemKindProperty"] = true,
  ["CmpItemKindEnum"] = true,
  ["CmpItemKindUnit"] = true,
  ["CmpItemKindClass"] = true,
  ["CmpItemKindFile"] = true,
  ["CmpItemKindInterface"] = true,
  ["CmpItemKindColor"] = true,
  ["CmpItemKindReference"] = true,
  ["CmpItemKindEnumMember"] = true,
  ["CmpItemKindStruct"] = true,
  ["CmpItemKindValue"] = true,
  ["CmpItemKindEvent"] = true,
  ["CmpItemKindOperator"] = true,
  ["CmpItemKindTypeParameter"] = true,
  ["CmpItemKindCopilot"] = true,
  ["CmpBorder"] = true,
  ["IndentBlanklineChar"] = true,
  ["IndentBlanklineSpaceChar"] = true,
  ["IndentBlanklineContextStart"] = true,
  ["IndentBlanklineContextChar"] = true,
  ["ExtendedHLGroups"] = true,
  ["NotifyTRACEBorder"] = true,
  ["NotifyTRACEIcon"] = true,
  ["NotifyTRACETitle"] = true,
  ["NotifyERRORBorder"] = true,
  ["NotifyERRORIcon"] = true,
  ["NotifyERRORTitle"] = true,
  ["NotifyWARNBorder"] = true,
  ["NotifyWARNIcon"] = true,
  ["NotifyWARNTitle"] = true,
  ["NotifyINFOBorder"] = true,
  ["NotifyINFOIcon"] = true,
  ["NotifyINFOTitle"] = true,
  ["NotifyDEBUGBorder"] = true,
  ["NotifyDEBUGIcon"] = true,
  ["NotifyDEBUGTitle"] = true,
  ["DapUIWatchesEmpty"] = true,
  ["DapUIFloatBorder"] = true,
  ["DapUILineNumber"] = true,
  ["DapUISource"] = true,
  ["DapUIStoppedThread"] = true,
  ["DapUIThread"] = true,
  ["DapUIDecoration"] = true,
  ["DapUIModifiedValue"] = true,
  ["DAPUIVariable"] = true,
  ["DAPUIValue"] = true,
  ["DAPUIType"] = true,
  ["DAPUIScope"] = true,
  ["DapStopped"] = true,
  ["DapLogPoint"] = true,
  ["DapBreakpointCondition"] = true,
  ["DapBreakpoint"] = true,
  ["DapUIUnavailable"] = true,
  ["DapUIRestart"] = true,
  ["DapUIPlayPause"] = true,
  ["DapUIStop"] = true,
  ["DapUIStepOut"] = true,
  ["DapUIStepBack"] = true,
  ["DapUIStepInto"] = true,
  ["DapUIStepOver"] = true,
  ["DapUIBreakpointsDisabledLine"] = true,
  ["DapUIBreakPointsCurrentLine"] = true,
  ["DapUIBreakpointsInfo"] = true,
  ["DapUIBreakpointsPath"] = true,
  ["DapUIWatchesError"] = true,
  ["DapUIWatchesValue"] = true,
  ["BufferlineIndicatorVisible"] = true,
  ["BufferLineBufferSelected"] = true,
  ["BufferLineBufferVisible"] = true,
  ["BufferLineError"] = true,
  ["BufferLineErrorDiagnostic"] = true,
  ["BufferLineCloseButton"] = true,
  ["BufferLineCloseButtonVisible"] = true,
  ["BufferLineCloseButtonSelected"] = true,
  ["BufferLineFill"] = true,
  ["BufferlineIndicatorSelected"] = true,
  ["BufferLineModified"] = true,
  ["BufferLineModifiedVisible"] = true,
  ["BufferLineModifiedSelected"] = true,
  ["BufferLineSeparator"] = true,
  ["BufferLineSeparatorVisible"] = true,
  ["BufferLineSeparatorSelected"] = true,
  ["BufferLineTab"] = true,
  ["BufferLineTabSelected"] = true,
  ["BufferLineTabClose"] = true,
  ["BufferLineDevIconDefaultSelected"] = true,
  ["BufferLineDevIconDefaultInactive"] = true,
  ["BufferLineDuplicate"] = true,
  ["BufferLineDuplicateSelected"] = true,
  ["BufferLineDuplicateVisible"] = true,
  ["BufferLineRightCustomAreaText1"] = true,
  ["BufferLineRightCustomAreaText2"] = true,
  ["BufferLineBackground"] = true,
  ["AlphaHeader"] = true,
  ["AlphaButtons"] = true,
}

local theme = {
  ColorColumn = { bg = "o_bluegray1" },
  Conceal = { bg = "NONE" },
  CurSearch = { link = "IncSearch", bold = true },
  CursorColumn = { bg = "o_background1" },
  CursorLine = { bg = 'o_background1'  },
  CursorLineNr = { fg = "o_text" },
  DarkenedPanel = { bg = "g_panel" },
  DarkenedStatusline = { bg = "g_panel" },
  diffAdded = { link = "DiffAdd" },
  diffChanged = { link = "DiffChange" },
  diffRemoved = { link = "DiffDelete" },
  Directory = { fg = "o_blue3", bg = "NONE" },
  ErrorMsg = { fg = "o_pink3", bold = true },
  FloatBorder = { fg = "g_border" },
  FloatTitle = { fg = "o_bluegray2" },
  FoldColumn = { fg = "o_bluegray2" },
  Folded = { fg = "o_text", bg = "g_panel" },
  IncSearch = { fg = "o_background3", bg = "o_blue2", bold = true },
  LineNr = { fg = "o_bluegray3" },
  MatchParen = { bg = "o_bluegray3", fg = "o_background3" },
  ModeMsg = { fg = "o_blue3" },
  MoreMsg = { fg = "o_blue3" },
  NonText = { fg = "o_blue4" },
  Normal = { fg = "o_text", bg = "g_background" },
  NormalFloat = { fg = "o_text", bg = "g_panel" },
  NormalNC = { fg = "o_text", bg = "g_background" },
  NvimInternalError = { fg = "o_white", bg = "o_pink3" },
  Pmenu = { fg = "o_bluegray1", bg = "g_panel" },
  PmenuSbar = { bg = "o_bluegray2" },
  PmenuSel = { fg = "o_text", bg = "o_background1" },
  PmenuThumb = { bg = "o_bluegray3" },
  Question = { fg = "o_yellow" },
  RedrawDebugClear = { fg = "o_white", bg = "o_yellow" },
  RedrawDebugComposed = { fg = "o_white", bg = "o_teal2" },
  RedrawDebugRecompose = { fg = "o_white", bg = "o_pink3" },
  Search = { bg = { "o_bluegray1", 30 } },
  SpecialKey = { fg = "o_teal1" },
  SpellBad = { sp = "o_pink3", undercurl = true },
  SpellCap = { sp = "o_blue1", undercurl = true },
  SpellLocal = { sp = "o_yellow", undercurl = true },
  SpellRare = { sp = "o_blue1", undercurl = true },
  SignColumn = { fg = "o_text", bg = "NONE" },
  StatusLine = { fg = "o_blue3", bg = "g_panel" },
  StatusLineNC = { fg = "o_blue3", bg = "g_background" },
  StatusLineTerm = { link = "StatusLine" },
  StatusLineTermNC = { link = "StatusLineNC" },
  TabLine = { fg = "o_blue3", bg = "g_panel" },
  TabLineFill = { bg = "g_panel" },
  TabLineSel = { fg = "o_text", bg = "o_background1" },
  Title = { fg = "o_text" },
  VertSplit = { fg = "NONE", bg = "NONE" },
  Visual = { fg = "o_text", bg = "o_bluegray3" },
  WarningMsg = { fg = "o_yellow" },
  Whitespace = { fg = "o_bluegray3" },
  WildMenu = { link = "IncSearch" },

  Constant = { fg = "o_text" },
  String = { fg = "o_text" },
  Character = { fg = "o_pink3" },
  Number = { fg = "o_teal1" },
  Boolean = { fg = "o_teal1" },
  Float = { fg = "o_teal1" },

  Identifier = { fg = "o_bluegray1" },
  Function = { fg = "o_blue2" },

  Statement = { fg = "o_text" },
  Conditional = { fg = "o_bluegray1" },
  Repeat = { fg = "o_blue3" },
  Label = { fg = "o_text" },
  Operator = { fg = "o_blue2" },
  Keyword = { fg = "o_blue3" },
  Exception = { fg = "o_blue3" },
  PreProc = { fg = "o_text" },
  Include = { fg = "o_bluegray1" },
  Type = { fg = "o_bluegray1" },
  Special = { fg = "o_bluegray2" },
  Tag = { fg = "o_text" },
  Delimiter = { fg = "o_bluegray1" },
  SpecialComment = { fg = "o_bluegray1" },
  -- Comment
  Comment = { fg = "o_bluegray3" },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = "o_pink3" },
  Todo = { bg = "None", fg = "red", nocombine = true },
  qfLineNr = { fg = "o_bluegray3" },
  qfFileName = { fg = "o_bluegray2" },
  htmlH1 = { fg = "o_teal1", bold = true },
  htmlH2 = { fg = "o_teal1", bold = true },
  mkdCodeDelimiter = { bg = "o_background3", fg = "o_text" },
  mkdCodeStart = { fg = "o_teal2", bold = true },
  mkdCodeEnd = { fg = "o_teal2", bold = true },
  mkdLink = { fg = "o_blue1", underline = true },
  markdownHeadingDelimiter = { fg = "o_blue4", bold = true },
  markdownCode = { fg = "o_bluegray1" },
  markdownCodeBlock = { fg = "o_teal2" },
  markdownH1 = { fg = "o_blue2", bold = true },
  markdownH2 = { fg = "o_blue2", bold = true },
  markdownH3 = { fg = "o_blue2", bold = true },
  markdownH4 = { fg = "o_blue2", bold = true },
  markdownLinkText = { fg = "o_blue1", underline = true },

  DiagnosticError = { fg = "g_error" },
  DiagnosticHint = { fg = "g_hint" },
  DiagnosticInfo = { fg = "g_info" },
  DiagnosticWarn = { fg = "g_warn" },
  DiagnosticDefaultError = { fg = "g_error" },
  DiagnosticDefaultHint = { fg = "g_hint" },
  DiagnosticDefaultInfo = { fg = "g_info" },
  DiagnosticDefaultWarn = { fg = "g_warn" },
  DiagnosticFloatingError = { fg = "g_error" },
  DiagnosticFloatingHint = { fg = "g_hint" },
  DiagnosticFloatingInfo = { fg = "g_info" },
  DiagnosticFloatingWarn = { fg = "g_warn" },
  DiagnosticSignError = { fg = "g_error" },
  DiagnosticSignHint = { fg = "g_hint" },
  DiagnosticSignInfo = { fg = "g_info" },
  DiagnosticSignWarn = { fg = "g_warn" },
  DiagnosticStatusLineError = { fg = "g_error", bg = "g_panel" },
  DiagnosticStatusLineHint = { fg = "g_hint", bg = "g_panel" },
  DiagnosticStatusLineInfo = { fg = "g_info", bg = "g_panel" },
  DiagnosticStatusLineWarn = { fg = "g_warn", bg = "g_panel" },
  DiagnosticUnderlineError = { sp = "g_error", undercurl = true },
  DiagnosticUnderlineHint = { sp = "g_hint", undercurl = true },
  DiagnosticUnderlineInfo = { sp = "g_info", undercurl = true },
  DiagnosticUnderlineWarn = { sp = "g_warn", undercurl = true },
  DiagnosticVirtualTextError = { fg = "g_error" },
  DiagnosticVirtualTextHint = { fg = "g_hint" },
  DiagnosticVirtualTextInfo = { fg = "g_info" },
  DiagnosticVirtualTextWarn = { fg = "g_warn" },

  ["@variable"] = { fg = "o_text" },
  ["@boolean"] = { link = "Boolean" },
  ["@comment"] = { link = "Comment" },
  ["@variable.builtin"] = { fg = "o_blue2" },
  ["@constant.builtin"] = { fg = "o_blue2" },
  ["@constant.falsy"] = { fg = "o_pink3" },
  ["@constructor"] = { fg = "o_teal1" },
  ["field"] = { fg = "o_text" },
  ["@function.builtin"] = { fg = "o_blue2" },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = "o_bluegray1" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = "o_teal2" },
  ["@keyword.function"] = { fg = "o_blue2" },
  ["@keyword.operator"] = { fg = "o_teal1" },
  ["@label"] = { fg = "o_blue3" },
  ["@method"] = { fg = "o_teal1" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { fg = "o_text" },
  ["@property"] = { fg = "o_blue2" },
  ["@punctuation.delimiter"] = { fg = "g_punctuation" },
  ["@punctuation.special"] = { fg = "g_punctuation" },
  ["@punctuation.bracket"] = { fg = "o_text" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = "o_pink3" },
  ["@tag"] = { fg = "o_teal1" },
  ["@tag.delimiter"] = { fg = "o_text" },
  ["@tag.attribute"] = { fg = "o_blue3" },
  ["@text"] = { fg = "o_text" },
  ["@text.uri"] = { fg = "g_link" },
  ["@title"] = { fg = "g_h1", bold = true },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Type" },

  LspReferenceText = { bg = "o_blue2" },
  LspReferenceRead = { bg = "o_blue2" },
  LspReferenceWrite = { bg = "o_blue2" },
  LspCodeLens = { fg = "o_bluegray1" },
  LspCodeLensSeparator = { fg = "o_bluegray3" },

  GitSignsAdd = { fg = "g_git_add" },
  GitSignsChange = { fg = "g_git_change" },
  GitSignsDelete = { fg = "g_git_delete" },
  SignAdd = { link = "GitSignsAdd" },
  SignChange = { link = "GitSignsChange" },
  SignDelete = { link = "GitSignsDelete" },

  NvimTreeCursorLine = {link = "CursorLine"},
  NvimTreeEmptyFolderName = { fg = "o_bluegray3" },
  NvimTreeFileDeleted = { fg = "o_pink3" },
  NvimTreeFileDirty = { fg = "o_blue4" },
  NvimTreeFileMerge = { fg = "o_blue2" },
  NvimTreeFileNew = { fg = "o_teal1" },
  NvimTreeFileRenamed = { fg = "o_bluegray3" },
  NvimTreeFileStaged = { fg = "o_blue1" },
  NvimTreeFolderIcon = { fg = "o_blue3" },
  NvimTreeFolderName = { fg = "o_blue3" },
  NvimTreeGitDeleted = { fg = "g_git_delete" },
  NvimTreeGitDirty = { fg = "g_git_dirty" },
  NvimTreeGitIgnored = { fg = "g_git_ignore" },
  NvimTreeGitMerge = { fg = "g_git_merge" },
  NvimTreeGitNew = { fg = "g_git_add" },
  NvimTreeGitRenamed = { fg = "g_git_rename" },
  NvimTreeGitStaged = { fg = "g_git_stage" },
  NvimTreeImageFile = { fg = "o_text" },
  NvimTreeNormal = { fg = "o_text" },
  NvimTreeOpenedFile = { fg = "o_text", bg = "o_background1" },
  NvimTreeOpenedFolderName = { link = "NvimTreeFolderName" },
  NvimTreeRootFolder = { fg = "o_teal1" },
  NvimTreeSpecialFile = { link = "NvimTreeNormal" },
  NvimTreeWindowPicker = { fg = "g_bg", bg = "o_bluegray1" },

  WhichKey = { fg = "o_text" },
  WhichKeyGroup = { fg = "o_text" },
  WhichKeySeparator = { fg = "o_text" },
  WhichKeyDesc = { fg = "o_text" },
  WhichKeyFloat = { bg = "g_panel" },
  WhichKeyValue = { fg = "o_text" },

  IndentBlanklineChar = { fg = "o_background1" },
  IndentBlanklineContextChar = { fg = "o_bluegray2", nocombine = true },
  IndentBlanklineContextStart = { sp = "o_bluegray2", underline = true },
  IndentBlanklineSpaceChar = { link = "Whitespace" },
  IndentBlanklineSpaceCharBlankline = { link = "Whitespace" },

  IlluminatedWordRead = { bg = { "o_background1", 10 } },
  IlluminatedWordText = { bg = { "o_background1", 10 } },
  IlluminatedWordWrite = { bg = { "o_background1", 10 } },

  CmpItemAbbr = { fg = "o_bluegray2" },
  CmpItemAbbrDeprecated = { fg = "o_pink3", strikethrough = true },
  CmpItemAbbrMatch = { fg = "o_text", bold = true },
  CmpItemAbbrMatchFuzzy = { fg = "o_teal1", bold = true },
  CmpItemKind = { fg = "o_blue3" },
  CmpItemKindClass = { fg = "o_yellow" },
  CmpItemKindFunction = { fg = "o_blue1" },
  CmpItemKindInterface = { fg = "o_blue2" },
  CmpItemKindMethod = { fg = "o_pink3" },
  CmpItemKindSnippet = { fg = "o_bluegray1" },
  CmpItemKindVariable = { fg = "o_teal1" },

  LspSignatureActiveParameter = { bg = "o_bluegray1" },

  PounceAccept = { fg = "o_pink3", bg = "o_text" },
  PounceAcceptBest = { fg = "o_text", bg = "o_text" },
  PounceGap = { link = "Search" },
  PounceMatch = { link = "Search" },

  TelescopeBorder = { fg = "g_border" },
  TelescopeMatching = { fg = "o_teal1" },
  TelescopeNormal = { fg = "o_text" },
  TelescopePromptNormal = { fg = "o_text" },
  TelescopePromptPrefix = { fg = "o_bluegray1" },
  TelescopeSelection = { fg = "o_text", bg = "o_bluegray1" },
  TelescopeSelectionCaret = { fg = "o_pink2", bg = "o_bluegray1" },
  TelescopeTitle = { fg = "o_bluegray2" },

  HopNextKey = { fg = "o_blue1" },
  HopNextKey1 = { fg = "o_teal1" },
  HopNextKey2 = { fg = "o_teal2" },
  HopUnmatched = { fg = "o_bluegray3" },
  HopCursor = { fg = "o_blue3" },

  NotifyINFOBorder = { fg = "o_teal1" },
  NotifyINFOTitle = { link = "NotifyINFOBorder" },
  NotifyINFOIcon = { link = "NotifyINFOBorder" },
  NotifyWARNBorder = { fg = "o_yellow" },
  NotifyWARNTitle = { link = "NotifyWARNBorder" },
  NotifyWARNIcon = { link = "NotifyWARNBorder" },
  NotifyDEBUGBorder = { fg = "o_blue1" },
  NotifyDEBUGTitle = { link = "NotifyDEBUGBorder" },
  NotifyDEBUGIcon = { link = "NotifyDEBUGBorder" },
  NotifyTRACEBorder = { fg = "o_blue1" },
  NotifyTRACETitle = { link = "NotifyTRACEBorder" },
  NotifyTRACEIcon = { link = "NotifyTRACEBorder" },
  NotifyERRORBorder = { fg = "o_pink3" },
  NotifyERRORTitle = { link = "NotifyERRORBorder" },
  NotifyERRORIcon = { link = "NotifyERRORBorder" },
}

local function generate()
  local M = {
    override = {},
    add = {},
  }
  for key, val in pairs(theme) do
    if predefined[key] then
      M.override[key] = val
    else
      M.add[key] = val
    end
  end

  return M
end

return generate()
